on:
  push:
    branches: [main]
jobs:
  merge_commit_title_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: tokghwt/test-action@v1
        with:
          pattern: '^(?:(?:feat|fix|refactor|docs|test|chore)(?:\([^)]+\))?!?: [A-Z].*[^ ]|release: v[0-9]+\.[0-9]+\.[0-9]+|revert: ".+") \(#[1-9][0-9]*\)$'
